---
abstract: 'Документация Perl по-русски'
author:
  - 'Команда Perl по-русски, Moscow-pm'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POD2-RU
no_index:
  directory:
    - t
    - inc
requires:
  POD2::Base: 0.043
  Pod::Perldoc: 3.15
  Test::More: 0
  Test::More::UTF8: 0.04
version: v5.18.0.1.02
